<?php
/**
 * @package Helix_Ultimate_Framework
 * @author JoomShaper <support@joomshaper.com>
 * @copyright Copyright (c) 2010 - 2020 JoomShaper
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 or Later
 */
namespace HelixUltimate\Framework\Core\Lib;

defined('_JEXEC') or die('restricted aceess');

/**
 * Class for font-awesome icons.
 *
 * @since	2.0.0
 */
class FontawesomeIcons
{
	/**
	 * Fontawesome 5 free icons
	 *
	 * @var		array	The icons class list
	 * @since	2.0.0
	 */
	private $fa5_classes = [
		'fab fa-500px',
        'fab fa-accessible-icon',
        'fab fa-accusoft',
        'fas fa-address-book',
        'far fa-address-book',
        'fas fa-address-card',
        'far fa-address-card',
        'fas fa-adjust',
        'fab fa-adn',
        'fab fa-adversal',
        'fab fa-affiliatetheme',
        'fab fa-algolia',
        'fas fa-align-center',
        'fas fa-align-justify',
        'fas fa-align-left',
        'fas fa-align-right',
        'fas fa-allergies',
        'fab fa-amazon',
        'fab fa-amazon-pay',
        'fas fa-ambulance',
        'fas fa-american-sign-language-interpreting',
        'fab fa-amilia',
        'fas fa-anchor',
        'fab fa-android',
        'fab fa-angellist',
        'fas fa-angle-double-down',
        'fas fa-angle-double-left',
        'fas fa-angle-double-right',
        'fas fa-angle-double-up',
        'fas fa-angle-down',
        'fas fa-angle-left',
        'fas fa-angle-right',
        'fas fa-angle-up',
        'fab fa-angrycreative',
        'fab fa-angular',
        'fab fa-app-store',
        'fab fa-app-store-ios',
        'fab fa-apper',
        'fab fa-apple',
        'fab fa-apple-pay',
        'fas fa-archive',
        'fas fa-arrow-alt-circle-down',
        'far fa-arrow-alt-circle-down',
        'fas fa-arrow-alt-circle-left',
        'far fa-arrow-alt-circle-left',
        'fas fa-arrow-alt-circle-right',
        'far fa-arrow-alt-circle-right',
        'fas fa-arrow-alt-circle-up',
        'far fa-arrow-alt-circle-up',
        'fas fa-arrow-circle-down',
        'fas fa-arrow-circle-left',
        'fas fa-arrow-circle-right',
        'fas fa-arrow-circle-up',
        'fas fa-arrow-down',
        'fas fa-arrow-left',
        'fas fa-arrow-right',
        'fas fa-arrow-up',
        'fas fa-arrows-alt',
        'fas fa-arrows-alt-h',
        'fas fa-arrows-alt-v',
        'fas fa-assistive-listening-systems',
        'fas fa-asterisk',
        'fab fa-asymmetrik',
        'fas fa-at',
        'fab fa-audible',
        'fas fa-audio-description',
        'fab fa-autoprefixer',
        'fab fa-avianex',
        'fab fa-aviato',
        'fab fa-aws',
        'fas fa-backward',
        'fas fa-balance-scale',
        'fas fa-ban',
        'fas fa-band-aid',
        'fab fa-bandcamp',
        'fas fa-barcode',
        'fas fa-bars',
        'fas fa-baseball-ball',
        'fas fa-basketball-ball',
        'fas fa-bath',
        'fas fa-battery-empty',
        'fas fa-battery-full',
        'fas fa-battery-half',
        'fas fa-battery-quarter',
        'fas fa-battery-three-quarters',
        'fas fa-bed',
        'fas fa-beer',
        'fab fa-behance',
        'fab fa-behance-square',
        'fas fa-bell',
        'far fa-bell',
        'fas fa-bell-slash',
        'far fa-bell-slash',
        'fas fa-bicycle',
        'fab fa-bimobject',
        'fas fa-binoculars',
        'fas fa-birthday-cake',
        'fab fa-bitbucket',
        'fab fa-bitcoin',
        'fab fa-bity',
        'fab fa-black-tie',
        'fab fa-blackberry',
        'fas fa-blind',
        'fab fa-blogger',
        'fab fa-blogger-b',
        'fab fa-bluetooth',
        'fab fa-bluetooth-b',
        'fas fa-bold',
        'fas fa-bolt',
        'fas fa-bomb',
        'fas fa-book',
        'fas fa-bookmark',
        'far fa-bookmark',
        'fas fa-bowling-ball',
        'fas fa-box',
        'fas fa-box-open',
        'fas fa-boxes',
        'fas fa-braille',
        'fas fa-briefcase',
        'fas fa-briefcase-medical',
        'fab fa-btc',
        'fas fa-bug',
        'fas fa-building',
        'far fa-building',
        'fas fa-bullhorn',
        'fas fa-bullseye',
        'fas fa-burn',
        'fab fa-buromobelexperte',
        'fas fa-bus',
        'fab fa-buysellads',
        'fas fa-calculator',
        'fas fa-calendar',
        'far fa-calendar',
        'fas fa-calendar-alt',
        'far fa-calendar-alt',
        'fas fa-calendar-check',
        'far fa-calendar-check',
        'fas fa-calendar-minus',
        'far fa-calendar-minus',
        'fas fa-calendar-plus',
        'far fa-calendar-plus',
        'fas fa-calendar-times',
        'far fa-calendar-times',
        'fas fa-camera',
        'fas fa-camera-retro',
        'fas fa-capsules',
        'fas fa-car',
        'fas fa-caret-down',
        'fas fa-caret-left',
        'fas fa-caret-right',
        'fas fa-caret-square-down',
        'far fa-caret-square-down',
        'fas fa-caret-square-left',
        'far fa-caret-square-left',
        'fas fa-caret-square-right',
        'far fa-caret-square-right',
        'fas fa-caret-square-up',
        'far fa-caret-square-up',
        'fas fa-caret-up',
        'fas fa-cart-arrow-down',
        'fas fa-cart-plus',
        'fab fa-cc-amazon-pay',
        'fab fa-cc-amex',
        'fab fa-cc-apple-pay',
        'fab fa-cc-diners-club',
        'fab fa-cc-discover',
        'fab fa-cc-jcb',
        'fab fa-cc-mastercard',
        'fab fa-cc-paypal',
        'fab fa-cc-stripe',
        'fab fa-cc-visa',
        'fab fa-centercode',
        'fas fa-certificate',
        'fas fa-chart-area',
        'fas fa-chart-bar',
        'far fa-chart-bar',
        'fas fa-chart-line',
        'fas fa-chart-pie',
        'fas fa-check',
        'fas fa-check-circle',
        'far fa-check-circle',
        'fas fa-check-square',
        'far fa-check-square',
        'fas fa-chess',
        'fas fa-chess-bishop',
        'fas fa-chess-board',
        'fas fa-chess-king',
        'fas fa-chess-knight',
        'fas fa-chess-pawn',
        'fas fa-chess-queen',
        'fas fa-chess-rook',
        'fas fa-chevron-circle-down',
        'fas fa-chevron-circle-left',
        'fas fa-chevron-circle-right',
        'fas fa-chevron-circle-up',
        'fas fa-chevron-down',
        'fas fa-chevron-left',
        'fas fa-chevron-right',
        'fas fa-chevron-up',
        'fas fa-child',
        'fab fa-chrome',
        'fas fa-circle',
        'far fa-circle',
        'fas fa-circle-notch',
        'fas fa-clipboard',
        'far fa-clipboard',
        'fas fa-clipboard-check',
        'fas fa-clipboard-list',
        'fas fa-clock',
        'far fa-clock',
        'fas fa-clone',
        'far fa-clone',
        'fas fa-closed-captioning',
        'far fa-closed-captioning',
        'fas fa-cloud',
        'fas fa-cloud-download-alt',
        'fas fa-cloud-upload-alt',
        'fab fa-cloudscale',
        'fab fa-cloudsmith',
        'fab fa-cloudversify',
        'fas fa-code',
        'fas fa-code-branch',
        'fab fa-codepen',
        'fab fa-codiepie',
        'fas fa-coffee',
        'fas fa-cog',
        'fas fa-cogs',
        'fas fa-columns',
        'fas fa-comment',
        'far fa-comment',
        'fas fa-comment-alt',
        'far fa-comment-alt',
        'fas fa-comment-dots',
        'fas fa-comment-slash',
        'fas fa-comments',
        'far fa-comments',
        'fas fa-compass',
        'far fa-compass',
        'fas fa-compress',
        'fab fa-connectdevelop',
        'fab fa-contao',
        'fas fa-copy',
        'far fa-copy',
        'fas fa-copyright',
        'far fa-copyright',
        'fas fa-couch',
        'fab fa-cpanel',
        'fab fa-creative-commons',
        'fas fa-credit-card',
        'far fa-credit-card',
        'fas fa-crop',
        'fas fa-crosshairs',
        'fab fa-css3',
        'fab fa-css3-alt',
        'fas fa-cube',
        'fas fa-cubes',
        'fas fa-cut',
        'fab fa-cuttlefish',
        'fab fa-d-and-d',
        'fab fa-dashcube',
        'fas fa-database',
        'fas fa-deaf',
        'fab fa-delicious',
        'fab fa-deploydog',
        'fab fa-deskpro',
        'fas fa-desktop',
        'fab fa-deviantart',
        'fas fa-diagnoses',
        'fab fa-digg',
        'fab fa-digital-ocean',
        'fab fa-discord',
        'fab fa-discourse',
        'fas fa-dna',
        'fab fa-dochub',
        'fab fa-docker',
        'fas fa-dollar-sign',
        'fas fa-dolly',
        'fas fa-dolly-flatbed',
        'fas fa-donate',
        'fas fa-dot-circle',
        'far fa-dot-circle',
        'fas fa-dove',
        'fas fa-download',
        'fab fa-draft2digital',
        'fab fa-dribbble',
        'fab fa-dribbble-square',
        'fab fa-dropbox',
        'fab fa-drupal',
        'fab fa-dyalog',
        'fab fa-earlybirds',
        'fab fa-edge',
        'fas fa-edit',
        'far fa-edit',
        'fas fa-eject',
        'fab fa-elementor',
        'fas fa-ellipsis-h',
        'fas fa-ellipsis-v',
        'fab fa-ember',
        'fab fa-empire',
        'fas fa-envelope',
        'far fa-envelope',
        'fas fa-envelope-open',
        'far fa-envelope-open',
        'fas fa-envelope-square',
        'fab fa-envira',
        'fas fa-eraser',
        'fab fa-erlang',
        'fab fa-ethereum',
        'fab fa-etsy',
        'fas fa-euro-sign',
        'fas fa-exchange-alt',
        'fas fa-exclamation',
        'fas fa-exclamation-circle',
        'fas fa-exclamation-triangle',
        'fas fa-expand',
        'fas fa-expand-arrows-alt',
        'fab fa-expeditedssl',
        'fas fa-external-link-alt',
        'fas fa-external-link-square-alt',
        'fas fa-eye',
        'fas fa-eye-dropper',
        'fas fa-eye-slash',
        'far fa-eye-slash',
        'fab fa-facebook',
        'fab fa-facebook-f',
        'fab fa-facebook-messenger',
        'fab fa-facebook-square',
        'fas fa-fast-backward',
        'fas fa-fast-forward',
        'fas fa-fax',
        'fas fa-female',
        'fas fa-fighter-jet',
        'fas fa-file',
        'far fa-file',
        'fas fa-file-alt',
        'far fa-file-alt',
        'fas fa-file-archive',
        'far fa-file-archive',
        'fas fa-file-audio',
        'far fa-file-audio',
        'fas fa-file-code',
        'far fa-file-code',
        'fas fa-file-excel',
        'far fa-file-excel',
        'fas fa-file-image',
        'far fa-file-image',
        'fas fa-file-medical',
        'fas fa-file-medical-alt',
        'fas fa-file-pdf',
        'far fa-file-pdf',
        'fas fa-file-powerpoint',
        'far fa-file-powerpoint',
        'fas fa-file-video',
        'far fa-file-video',
        'fas fa-file-word',
        'far fa-file-word',
        'fas fa-film',
        'fas fa-filter',
        'fas fa-fire',
        'fas fa-fire-extinguisher',
        'fab fa-firefox',
        'fas fa-first-aid',
        'fab fa-first-order',
        'fab fa-firstdraft',
        'fas fa-flag',
        'far fa-flag',
        'fas fa-flag-checkered',
        'fas fa-flask',
        'fab fa-flickr',
        'fab fa-flipboard',
        'fab fa-fly',
        'fas fa-folder',
        'far fa-folder',
        'fas fa-folder-open',
        'far fa-folder-open',
        'fas fa-font',
        'fab fa-font-awesome',
        'fab fa-font-awesome-alt',
        'fab fa-font-awesome-flag',
        'fab fa-fonticons',
        'fab fa-fonticons-fi',
        'fas fa-football-ball',
        'fab fa-fort-awesome',
        'fab fa-fort-awesome-alt',
        'fab fa-forumbee',
        'fas fa-forward',
        'fab fa-foursquare',
        'fab fa-free-code-camp',
        'fab fa-freebsd',
        'fas fa-frown',
        'far fa-frown',
        'fas fa-futbol',
        'far fa-futbol',
        'fas fa-gamepad',
        'fas fa-gavel',
        'fas fa-gem',
        'far fa-gem',
        'fas fa-genderless',
        'fab fa-get-pocket',
        'fab fa-gg',
        'fab fa-gg-circle',
        'fas fa-gift',
        'fab fa-git',
        'fab fa-git-square',
        'fab fa-github',
        'fab fa-github-alt',
        'fab fa-github-square',
        'fab fa-gitkraken',
        'fab fa-gitlab',
        'fab fa-gitter',
        'fas fa-glass-martini',
        'fab fa-glide',
        'fab fa-glide-g',
        'fas fa-globe',
        'fab fa-gofore',
        'fas fa-golf-ball',
        'fab fa-goodreads',
        'fab fa-goodreads-g',
        'fab fa-google',
        'fab fa-google-drive',
        'fab fa-google-play',
        'fab fa-google-plus',
        'fab fa-google-plus-g',
        'fab fa-google-plus-square',
        'fab fa-google-wallet',
        'fas fa-graduation-cap',
        'fab fa-gratipay',
        'fab fa-grav',
        'fab fa-gripfire',
        'fab fa-grunt',
        'fab fa-gulp',
        'fas fa-h-square',
        'fab fa-hacker-news',
        'fab fa-hacker-news-square',
        'fas fa-hand-holding',
        'fas fa-hand-holding-heart',
        'fas fa-hand-holding-usd',
        'fas fa-hand-lizard',
        'far fa-hand-lizard',
        'fas fa-hand-paper',
        'far fa-hand-paper',
        'fas fa-hand-peace',
        'far fa-hand-peace',
        'fas fa-hand-point-down',
        'far fa-hand-point-down',
        'fas fa-hand-point-left',
        'far fa-hand-point-left',
        'fas fa-hand-point-right',
        'far fa-hand-point-right',
        'fas fa-hand-point-up',
        'far fa-hand-point-up',
        'fas fa-hand-pointer',
        'far fa-hand-pointer',
        'fas fa-hand-rock',
        'far fa-hand-rock',
        'fas fa-hand-scissors',
        'far fa-hand-scissors',
        'fas fa-hand-spock',
        'far fa-hand-spock',
        'fas fa-hands',
        'fas fa-hands-helping',
        'fas fa-handshake',
        'far fa-handshake',
        'fas fa-hashtag',
        'fas fa-hdd',
        'far fa-hdd',
        'fas fa-heading',
        'fas fa-headphones',
        'fas fa-heart',
        'far fa-heart',
        'fas fa-heartbeat',
        'fab fa-hips',
        'fab fa-hire-a-helper',
        'fas fa-history',
        'fas fa-hockey-puck',
        'fas fa-home',
        'fab fa-hooli',
        'fas fa-hospital',
        'far fa-hospital',
        'fas fa-hospital-alt',
        'fas fa-hospital-symbol',
        'fab fa-hotjar',
        'fas fa-hourglass',
        'far fa-hourglass',
        'fas fa-hourglass-end',
        'fas fa-hourglass-half',
        'fas fa-hourglass-start',
        'fab fa-houzz',
        'fab fa-html5',
        'fab fa-hubspot',
        'fas fa-i-cursor',
        'fas fa-id-badge',
        'far fa-id-badge',
        'fas fa-id-card',
        'far fa-id-card',
        'fas fa-id-card-alt',
        'fas fa-image',
        'far fa-image',
        'fas fa-images',
        'far fa-images',
        'fab fa-imdb',
        'fas fa-inbox',
        'fas fa-indent',
        'fas fa-industry',
        'fas fa-info',
        'fas fa-info-circle',
        'fab fa-instagram',
        'fab fa-internet-explorer',
        'fab fa-ioxhost',
        'fas fa-italic',
        'fab fa-itunes',
        'fab fa-itunes-note',
        'fab fa-java',
        'fab fa-jenkins',
        'fab fa-joget',
        'fab fa-joomla',
        'fab fa-js',
        'fab fa-js-square',
        'fab fa-jsfiddle',
        'fas fa-key',
        'fas fa-keyboard',
        'far fa-keyboard',
        'fab fa-keycdn',
        'fab fa-kickstarter',
        'fab fa-kickstarter-k',
        'fab fa-korvue',
        'fas fa-language',
        'fas fa-laptop',
        'fab fa-laravel',
        'fab fa-lastfm',
        'fab fa-lastfm-square',
        'fas fa-leaf',
        'fab fa-leanpub',
        'fas fa-lemon',
        'far fa-lemon',
        'fab fa-less',
        'fas fa-level-down-alt',
        'fas fa-level-up-alt',
        'fas fa-life-ring',
        'far fa-life-ring',
        'fas fa-lightbulb',
        'far fa-lightbulb',
        'fab fa-line',
        'fas fa-link',
        'fab fa-linkedin',
        'fab fa-linkedin-in',
        'fab fa-linode',
        'fab fa-linux',
        'fas fa-lira-sign',
        'fas fa-list',
        'fas fa-list-alt',
        'far fa-list-alt',
        'fas fa-list-ol',
        'fas fa-list-ul',
        'fas fa-location-arrow',
        'fas fa-lock',
        'fas fa-lock-open',
        'fas fa-long-arrow-alt-down',
        'fas fa-long-arrow-alt-left',
        'fas fa-long-arrow-alt-right',
        'fas fa-long-arrow-alt-up',
        'fas fa-low-vision',
        'fab fa-lyft',
        'fab fa-magento',
        'fas fa-magic',
        'fas fa-magnet',
        'fas fa-male',
        'fas fa-map',
        'far fa-map',
        'fas fa-map-marker',
        'fas fa-map-marker-alt',
        'fas fa-map-pin',
        'fas fa-map-signs',
        'fas fa-mars',
        'fas fa-mars-double',
        'fas fa-mars-stroke',
        'fas fa-mars-stroke-h',
        'fas fa-mars-stroke-v',
        'fab fa-maxcdn',
        'fab fa-medapps',
        'fab fa-medium',
        'fab fa-medium-m',
        'fas fa-medkit',
        'fab fa-medrt',
        'fab fa-meetup',
        'fas fa-meh',
        'far fa-meh',
        'fas fa-mercury',
        'fas fa-microchip',
        'fas fa-microphone',
        'fas fa-microphone-slash',
        'fab fa-microsoft',
        'fas fa-minus',
        'fas fa-minus-circle',
        'fas fa-minus-square',
        'far fa-minus-square',
        'fab fa-mix',
        'fab fa-mixcloud',
        'fab fa-mizuni',
        'fas fa-mobile',
        'fas fa-mobile-alt',
        'fab fa-modx',
        'fab fa-monero',
        'fas fa-money-bill-alt',
        'far fa-money-bill-alt',
        'fas fa-moon',
        'far fa-moon',
        'fas fa-motorcycle',
        'fas fa-mouse-pointer',
        'fas fa-music',
        'fab fa-napster',
        'fas fa-neuter',
        'fas fa-newspaper',
        'far fa-newspaper',
        'fab fa-nintendo-switch',
        'fab fa-node',
        'fab fa-node-js',
        'fas fa-notes-medical',
        'fab fa-npm',
        'fab fa-ns8',
        'fab fa-nutritionix',
        'fas fa-object-group',
        'far fa-object-group',
        'fas fa-object-ungroup',
        'far fa-object-ungroup',
        'fab fa-odnoklassniki',
        'fab fa-odnoklassniki-square',
        'fab fa-opencart',
        'fab fa-openid',
        'fab fa-opera',
        'fab fa-optin-monster',
        'fab fa-osi',
        'fas fa-outdent',
        'fab fa-page4',
        'fab fa-pagelines',
        'fas fa-paint-brush',
        'fab fa-palfed',
        'fas fa-pallet',
        'fas fa-paper-plane',
        'far fa-paper-plane',
        'fas fa-paperclip',
        'fas fa-parachute-box',
        'fas fa-paragraph',
        'fas fa-paste',
        'fab fa-patreon',
        'fas fa-pause',
        'fas fa-pause-circle',
        'far fa-pause-circle',
        'fas fa-paw',
        'fab fa-paypal',
        'fas fa-pen-square',
        'fas fa-pencil-alt',
        'fas fa-people-carry',
        'fas fa-percent',
        'fab fa-periscope',
        'fab fa-phabricator',
        'fab fa-phoenix-framework',
        'fas fa-phone',
        'fas fa-phone-slash',
        'fas fa-phone-square',
        'fas fa-phone-volume',
        'fab fa-php',
        'fab fa-pied-piper',
        'fab fa-pied-piper-alt',
        'fab fa-pied-piper-hat',
        'fab fa-pied-piper-pp',
        'fas fa-piggy-bank',
        'fas fa-pills',
        'fab fa-pinterest',
        'fab fa-pinterest-p',
        'fab fa-pinterest-square',
        'fas fa-plane',
        'fas fa-play',
        'fas fa-play-circle',
        'far fa-play-circle',
        'fab fa-playstation',
        'fas fa-plug',
        'fas fa-plus',
        'fas fa-plus-circle',
        'fas fa-plus-square',
        'far fa-plus-square',
        'fas fa-podcast',
        'fas fa-poo',
        'fas fa-pound-sign',
        'fas fa-power-off',
        'fas fa-prescription-bottle',
        'fas fa-prescription-bottle-alt',
        'fas fa-print',
        'fas fa-procedures',
        'fab fa-product-hunt',
        'fab fa-pushed',
        'fas fa-puzzle-piece',
        'fab fa-python',
        'fab fa-qq',
        'fas fa-qrcode',
        'fas fa-question',
        'fas fa-question-circle',
        'far fa-question-circle',
        'fas fa-quidditch',
        'fab fa-quinscape',
        'fab fa-quora',
        'fas fa-quote-left',
        'fas fa-quote-right',
        'fas fa-random',
        'fab fa-ravelry',
        'fab fa-react',
        'fab fa-readme',
        'fab fa-rebel',
        'fas fa-recycle',
        'fab fa-red-river',
        'fab fa-reddit',
        'fab fa-reddit-alien',
        'fab fa-reddit-square',
        'fas fa-redo',
        'fas fa-redo-alt',
        'fas fa-registered',
        'far fa-registered',
        'fab fa-rendact',
        'fab fa-renren',
        'fas fa-reply',
        'fas fa-reply-all',
        'fab fa-replyd',
        'fab fa-resolving',
        'fas fa-retweet',
        'fas fa-ribbon',
        'fas fa-road',
        'fas fa-rocket',
        'fab fa-rocketchat',
        'fab fa-rockrms',
        'fas fa-rss',
        'fas fa-rss-square',
        'fas fa-ruble-sign',
        'fas fa-rupee-sign',
        'fab fa-safari',
        'fab fa-sass',
        'fas fa-save',
        'far fa-save',
        'fab fa-schlix',
        'fab fa-scribd',
        'fas fa-search',
        'fas fa-search-minus',
        'fas fa-search-plus',
        'fab fa-searchengin',
        'fas fa-seedling',
        'fab fa-sellcast',
        'fab fa-sellsy',
        'fas fa-server',
        'fab fa-servicestack',
        'fas fa-share',
        'fas fa-share-alt',
        'fas fa-share-alt-square',
        'fas fa-share-square',
        'far fa-share-square',
        'fas fa-shekel-sign',
        'fas fa-shield-alt',
        'fas fa-ship',
        'fas fa-shipping-fast',
        'fab fa-shirtsinbulk',
        'fas fa-shopping-bag',
        'fas fa-shopping-basket',
        'fas fa-shopping-cart',
        'fas fa-shower',
        'fas fa-sign',
        'fas fa-sign-in-alt',
        'fas fa-sign-language',
        'fas fa-sign-out-alt',
        'fas fa-signal',
        'fab fa-simplybuilt',
        'fab fa-sistrix',
        'fas fa-sitemap',
        'fab fa-skyatlas',
        'fab fa-skype',
        'fab fa-slack',
        'fab fa-slack-hash',
        'fas fa-sliders-h',
        'fab fa-slideshare',
        'fas fa-smile',
        'far fa-smile',
        'fas fa-smoking',
        'fab fa-snapchat',
        'fab fa-snapchat-ghost',
        'fab fa-snapchat-square',
        'fas fa-snowflake',
        'far fa-snowflake',
        'fas fa-sort',
        'fas fa-sort-alpha-down',
        'fas fa-sort-alpha-up',
        'fas fa-sort-amount-down',
        'fas fa-sort-amount-up',
        'fas fa-sort-down',
        'fas fa-sort-numeric-down',
        'fas fa-sort-numeric-up',
        'fas fa-sort-up',
        'fab fa-soundcloud',
        'fas fa-space-shuttle',
        'fab fa-speakap',
        'fas fa-spinner',
        'fab fa-spotify',
        'fas fa-square',
        'far fa-square',
        'fas fa-square-full',
        'fab fa-stack-exchange',
        'fab fa-stack-overflow',
        'fas fa-star',
        'far fa-star',
        'fas fa-star-half',
        'far fa-star-half',
        'fab fa-staylinked',
        'fab fa-steam',
        'fab fa-steam-square',
        'fab fa-steam-symbol',
        'fas fa-step-backward',
        'fas fa-step-forward',
        'fas fa-stethoscope',
        'fab fa-sticker-mule',
        'fas fa-sticky-note',
        'far fa-sticky-note',
        'fas fa-stop',
        'fas fa-stop-circle',
        'far fa-stop-circle',
        'fas fa-stopwatch',
        'fab fa-strava',
        'fas fa-street-view',
        'fas fa-strikethrough',
        'fab fa-stripe',
        'fab fa-stripe-s',
        'fab fa-studiovinari',
        'fab fa-stumbleupon',
        'fab fa-stumbleupon-circle',
        'fas fa-subscript',
        'fas fa-subway',
        'fas fa-suitcase',
        'fas fa-sun',
        'far fa-sun',
        'fab fa-superpowers',
        'fas fa-superscript',
        'fab fa-supple',
        'fas fa-sync',
        'fas fa-sync-alt',
        'fas fa-syringe',
        'fas fa-table',
        'fas fa-table-tennis',
        'fas fa-tablet',
        'fas fa-tablet-alt',
        'fas fa-tablets',
        'fas fa-tachometer-alt',
        'fas fa-tag',
        'fas fa-tags',
        'fas fa-tape',
        'fas fa-tasks',
        'fas fa-taxi',
        'fab fa-telegram',
        'fab fa-telegram-plane',
        'fab fa-tencent-weibo',
        'fas fa-terminal',
        'fas fa-text-height',
        'fas fa-text-width',
        'fas fa-th',
        'fas fa-th-large',
        'fas fa-th-list',
        'fab fa-themeisle',
        'fas fa-thermometer',
        'fas fa-thermometer-empty',
        'fas fa-thermometer-full',
        'fas fa-thermometer-half',
        'fas fa-thermometer-quarter',
        'fas fa-thermometer-three-quarters',
        'fas fa-thumbs-down',
        'far fa-thumbs-down',
        'fas fa-thumbs-up',
        'far fa-thumbs-up',
        'fas fa-thumbtack',
        'fas fa-ticket-alt',
        'fas fa-times',
        'fas fa-times-circle',
        'far fa-times-circle',
        'fas fa-tint',
        'fas fa-toggle-off',
        'fas fa-toggle-on',
        'fas fa-trademark',
        'fas fa-train',
        'fas fa-transgender',
        'fas fa-transgender-alt',
        'fas fa-trash',
        'fas fa-trash-alt',
        'far fa-trash-alt',
        'fas fa-tree',
        'fab fa-trello',
        'fab fa-tripadvisor',
        'fas fa-trophy',
        'fas fa-truck',
        'fas fa-truck-loading',
        'fas fa-truck-moving',
        'fas fa-tty',
        'fab fa-tumblr',
        'fab fa-tumblr-square',
        'fas fa-tv',
        'fab fa-twitch',
        'fab fa-twitter',
        'fab fa-twitter-square',
        'fab fa-typo3',
        'fab fa-uber',
        'fab fa-uikit',
        'fas fa-umbrella',
        'fas fa-underline',
        'fas fa-undo',
        'fas fa-undo-alt',
        'fab fa-uniregistry',
        'fas fa-universal-access',
        'fas fa-university',
        'fas fa-unlink',
        'fas fa-unlock',
        'fas fa-unlock-alt',
        'fab fa-untappd',
        'fas fa-upload',
        'fab fa-usb',
        'fas fa-user',
        'far fa-user',
        'fas fa-user-circle',
        'far fa-user-circle',
        'fas fa-user-md',
        'fas fa-user-plus',
        'fas fa-user-secret',
        'fas fa-user-times',
        'fas fa-users',
        'fab fa-ussunnah',
        'fas fa-utensil-spoon',
        'fas fa-utensils',
        'fab fa-vaadin',
        'fas fa-venus',
        'fas fa-venus-double',
        'fas fa-venus-mars',
        'fab fa-viacoin',
        'fab fa-viadeo',
        'fab fa-viadeo-square',
        'fas fa-vial',
        'fas fa-vials',
        'fab fa-viber',
        'fas fa-video',
        'fas fa-video-slash',
        'fab fa-vimeo',
        'fab fa-vimeo-square',
        'fab fa-vimeo-v',
        'fab fa-vine',
        'fab fa-vk',
        'fab fa-vnv',
        'fas fa-volleyball-ball',
        'fas fa-volume-down',
        'fas fa-volume-off',
        'fas fa-volume-up',
        'fab fa-vuejs',
        'fas fa-warehouse',
        'fab fa-weibo',
        'fas fa-weight',
        'fab fa-weixin',
        'fab fa-whatsapp',
        'fab fa-whatsapp-square',
        'fas fa-wheelchair',
        'fab fa-whmcs',
        'fas fa-wifi',
        'fab fa-wikipedia-w',
        'fas fa-window-close',
        'far fa-window-close',
        'fas fa-window-maximize',
        'far fa-window-maximize',
        'fas fa-window-minimize',
        'far fa-window-minimize',
        'fas fa-window-restore',
        'far fa-window-restore',
        'fab fa-windows',
        'fas fa-wine-glass',
        'fas fa-won-sign',
        'fab fa-wordpress',
        'fab fa-wordpress-simple',
        'fab fa-wpbeginner',
        'fab fa-wpexplorer',
        'fab fa-wpforms',
        'fas fa-wrench',
        'fas fa-x-ray',
        'fab fa-xbox',
        'fab fa-xing',
        'fab fa-xing-square',
        'fab fa-y-combinator',
        'fab fa-yahoo',
        'fab fa-yandex',
        'fab fa-yandex-international',
        'fab fa-yelp',
        'fas fa-yen-sign',
        'fab fa-yoast',
        'fab fa-youtube',
        'fab fa-youtube-square',
	];
	/**
	 * Font awesome icon class names.
	 *
	 * @var		array	Font-awesome class names.
	 * @since	2.0.0
	 */
	private $fa_class_lists = array(
		'fa-500px',
		'fa-adjust',
		'fa-adn',
		'fa-align-center',
		'fa-align-justify',
		'fa-align-left',
		'fa-align-right',
		'fa-amazon',
		'fa-ambulance',
		'fa-anchor',
		'fa-android',
		'fa-angellist',
		'fa-angle-double-down',
		'fa-angle-double-left',
		'fa-angle-double-right',
		'fa-angle-double-up',
		'fa-angle-down',
		'fa-angle-left',
		'fa-angle-right',
		'fa-angle-up',
		'fa-apple',
		'fa-archive',
		'fa-area-chart',
		'fa-arrow-circle-down',
		'fa-arrow-circle-left',
		'fa-arrow-circle-o-down',
		'fa-arrow-circle-o-left',
		'fa-arrow-circle-o-right',
		'fa-arrow-circle-o-up',
		'fa-arrow-circle-right',
		'fa-arrow-circle-up',
		'fa-arrow-down',
		'fa-arrow-left',
		'fa-arrow-right',
		'fa-arrow-up',
		'fa-arrows',
		'fa-arrows-alt',
		'fa-arrows-h',
		'fa-arrows-v',
		'fa-asterisk',
		'fa-at',
		'fa-automobile',
		'fa-backward',
		'fa-balance-scale',
		'fa-ban',
		'fa-bank',
		'fa-bar-chart',
		'fa-bar-chart-o',
		'fa-barcode',
		'fa-bars',
		'fa-battery-0',
		'fa-battery-1',
		'fa-battery-2',
		'fa-battery-3',
		'fa-battery-4',
		'fa-battery-empty',
		'fa-battery-full',
		'fa-battery-half',
		'fa-battery-quarter',
		'fa-battery-three-quarters',
		'fa-bed',
		'fa-beer',
		'fa-behance',
		'fa-behance-square',
		'fa-bell',
		'fa-bell-o',
		'fa-bell-slash',
		'fa-bell-slash-o',
		'fa-bicycle',
		'fa-binoculars',
		'fa-birthday-cake',
		'fa-bitbucket',
		'fa-bitbucket-square',
		'fa-bitcoin',
		'fa-black-tie',
		'fa-bluetooth',
		'fa-bluetooth-b',
		'fa-bold',
		'fa-bolt',
		'fa-bomb',
		'fa-book',
		'fa-bookmark',
		'fa-bookmark-o',
		'fa-briefcase',
		'fa-btc',
		'fa-bug',
		'fa-building',
		'fa-building-o',
		'fa-bullhorn',
		'fa-bullseye',
		'fa-bus',
		'fa-buysellads',
		'fa-cab',
		'fa-calculator',
		'fa-calendar',
		'fa-calendar-check-o',
		'fa-calendar-minus-o',
		'fa-calendar-o',
		'fa-calendar-plus-o',
		'fa-calendar-times-o',
		'fa-camera',
		'fa-camera-retro',
		'fa-car',
		'fa-caret-down',
		'fa-caret-left',
		'fa-caret-right',
		'fa-caret-square-o-down',
		'fa-caret-square-o-left',
		'fa-caret-square-o-right',
		'fa-caret-square-o-up',
		'fa-caret-up',
		'fa-cart-arrow-down',
		'fa-cart-plus',
		'fa-cc',
		'fa-cc-amex',
		'fa-cc-diners-club',
		'fa-cc-discover',
		'fa-cc-jcb',
		'fa-cc-mastercard',
		'fa-cc-paypal',
		'fa-cc-stripe',
		'fa-cc-visa',
		'fa-certificate',
		'fa-chain',
		'fa-chain-broken',
		'fa-check',
		'fa-check-circle',
		'fa-check-circle-o',
		'fa-check-square',
		'fa-check-square-o',
		'fa-chevron-circle-down',
		'fa-chevron-circle-left',
		'fa-chevron-circle-right',
		'fa-chevron-circle-up',
		'fa-chevron-down',
		'fa-chevron-left',
		'fa-chevron-right',
		'fa-chevron-up',
		'fa-child',
		'fa-chrome',
		'fa-circle',
		'fa-circle-o',
		'fa-circle-o-notch',
		'fa-circle-thin',
		'fa-clipboard',
		'fa-clock-o',
		'fa-clone',
		'fa-close',
		'fa-cloud',
		'fa-cloud-download',
		'fa-cloud-upload',
		'fa-cny',
		'fa-code',
		'fa-code-fork',
		'fa-codepen',
		'fa-codiepie',
		'fa-coffee',
		'fa-cog',
		'fa-cogs',
		'fa-columns',
		'fa-comment',
		'fa-comment-o',
		'fa-commenting',
		'fa-commenting-o',
		'fa-comments',
		'fa-comments-o',
		'fa-compass',
		'fa-compress',
		'fa-connectdevelop',
		'fa-contao',
		'fa-copy',
		'fa-copyright',
		'fa-creative-commons',
		'fa-credit-card',
		'fa-credit-card-alt',
		'fa-crop',
		'fa-crosshairs',
		'fa-css3',
		'fa-cube',
		'fa-cubes',
		'fa-cut',
		'fa-cutlery',
		'fa-dashboard',
		'fa-dashcube',
		'fa-database',
		'fa-dedent',
		'fa-delicious',
		'fa-desktop',
		'fa-deviantart',
		'fa-diamond',
		'fa-digg',
		'fa-dollar',
		'fa-dot-circle-o',
		'fa-download',
		'fa-dribbble',
		'fa-dropbox',
		'fa-drupal',
		'fa-edge',
		'fa-edit',
		'fa-eject',
		'fa-ellipsis-h',
		'fa-ellipsis-v',
		'fa-empire',
		'fa-envelope',
		'fa-envelope-o',
		'fa-envelope-square',
		'fa-eraser',
		'fa-eur',
		'fa-euro',
		'fa-exchange',
		'fa-exclamation',
		'fa-exclamation-circle',
		'fa-exclamation-triangle',
		'fa-expand',
		'fa-expeditedssl',
		'fa-external-link',
		'fa-external-link-square',
		'fa-eye',
		'fa-eye-slash',
		'fa-eyedropper',
		'fa-facebook',
		'fa-facebook-f',
		'fa-facebook-official',
		'fa-facebook-square',
		'fa-fast-backward',
		'fa-fast-forward',
		'fa-fax',
		'fa-feed',
		'fa-female',
		'fa-fighter-jet',
		'fa-file',
		'fa-file-archive-o',
		'fa-file-audio-o',
		'fa-file-code-o',
		'fa-file-excel-o',
		'fa-file-image-o',
		'fa-file-movie-o',
		'fa-file-o',
		'fa-file-pdf-o',
		'fa-file-photo-o',
		'fa-file-picture-o',
		'fa-file-powerpoint-o',
		'fa-file-sound-o',
		'fa-file-text',
		'fa-file-text-o',
		'fa-file-video-o',
		'fa-file-word-o',
		'fa-file-zip-o',
		'fa-files-o',
		'fa-film',
		'fa-filter',
		'fa-fire',
		'fa-fire-extinguisher',
		'fa-firefox',
		'fa-flag',
		'fa-flag-checkered',
		'fa-flag-o',
		'fa-flash',
		'fa-flask',
		'fa-flickr',
		'fa-floppy-o',
		'fa-folder',
		'fa-folder-o',
		'fa-folder-open',
		'fa-folder-open-o',
		'fa-font',
		'fa-fonticons',
		'fa-fort-awesome',
		'fa-forumbee',
		'fa-forward',
		'fa-foursquare',
		'fa-frown-o',
		'fa-futbol-o',
		'fa-gamepad',
		'fa-gavel',
		'fa-gbp',
		'fa-ge',
		'fa-gear',
		'fa-gears',
		'fa-genderless',
		'fa-get-pocket',
		'fa-gg',
		'fa-gg-circle',
		'fa-gift',
		'fa-git',
		'fa-git-square',
		'fa-github',
		'fa-github-alt',
		'fa-github-square',
		'fa-gittip',
		'fa-glass',
		'fa-globe',
		'fa-google',
		'fa-google-plus',
		'fa-google-plus-square',
		'fa-google-wallet',
		'fa-graduation-cap',
		'fa-gratipay',
		'fa-group',
		'fa-h-square',
		'fa-hacker-news',
		'fa-hand-grab-o',
		'fa-hand-lizard-o',
		'fa-hand-o-down',
		'fa-hand-o-left',
		'fa-hand-o-right',
		'fa-hand-o-up',
		'fa-hand-paper-o',
		'fa-hand-peace-o',
		'fa-hand-pointer-o',
		'fa-hand-rock-o',
		'fa-hand-scissors-o',
		'fa-hand-spock-o',
		'fa-hand-stop-o',
		'fa-hashtag',
		'fa-hdd-o',
		'fa-header',
		'fa-headphones',
		'fa-heart',
		'fa-heart-o',
		'fa-heartbeat',
		'fa-history',
		'fa-home',
		'fa-hospital-o',
		'fa-hotel',
		'fa-hourglass',
		'fa-hourglass-1',
		'fa-hourglass-2',
		'fa-hourglass-3',
		'fa-hourglass-end',
		'fa-hourglass-half',
		'fa-hourglass-o',
		'fa-hourglass-start',
		'fa-houzz',
		'fa-html5',
		'fa-i-cursor',
		'fa-ils',
		'fa-image',
		'fa-inbox',
		'fa-indent',
		'fa-industry',
		'fa-info',
		'fa-info-circle',
		'fa-inr',
		'fa-instagram',
		'fa-institution',
		'fa-internet-explorer',
		'fa-intersex',
		'fa-ioxhost',
		'fa-italic',
		'fa-joomla',
		'fa-jpy',
		'fa-jsfiddle',
		'fa-key',
		'fa-keyboard-o',
		'fa-krw',
		'fa-language',
		'fa-laptop',
		'fa-lastfm',
		'fa-lastfm-square',
		'fa-leaf',
		'fa-leanpub',
		'fa-legal',
		'fa-lemon-o',
		'fa-level-down',
		'fa-level-up',
		'fa-life-bouy',
		'fa-life-buoy',
		'fa-life-ring',
		'fa-life-saver',
		'fa-lightbulb-o',
		'fa-line-chart',
		'fa-link',
		'fa-linkedin',
		'fa-linkedin-square',
		'fa-linux',
		'fa-list',
		'fa-list-alt',
		'fa-list-ol',
		'fa-list-ul',
		'fa-location-arrow',
		'fa-lock',
		'fa-long-arrow-down',
		'fa-long-arrow-left',
		'fa-long-arrow-right',
		'fa-long-arrow-up',
		'fa-magic',
		'fa-magnet',
		'fa-mail-forward',
		'fa-mail-reply',
		'fa-mail-reply-all',
		'fa-male',
		'fa-map',
		'fa-map-marker',
		'fa-map-o',
		'fa-map-pin',
		'fa-map-signs',
		'fa-mars',
		'fa-mars-double',
		'fa-mars-stroke',
		'fa-mars-stroke-h',
		'fa-mars-stroke-v',
		'fa-maxcdn',
		'fa-meanpath',
		'fa-medium',
		'fa-medkit',
		'fa-meh-o',
		'fa-mercury',
		'fa-microphone',
		'fa-microphone-slash',
		'fa-minus',
		'fa-minus-circle',
		'fa-minus-square',
		'fa-minus-square-o',
		'fa-mixcloud',
		'fa-mobile',
		'fa-mobile-phone',
		'fa-modx',
		'fa-money',
		'fa-moon-o',
		'fa-mortar-board',
		'fa-motorcycle',
		'fa-mouse-pointer',
		'fa-music',
		'fa-navicon',
		'fa-neuter',
		'fa-newspaper-o',
		'fa-object-group',
		'fa-object-ungroup',
		'fa-odnoklassniki',
		'fa-odnoklassniki-square',
		'fa-opencart',
		'fa-openid',
		'fa-opera',
		'fa-optin-monster',
		'fa-outdent',
		'fa-pagelines',
		'fa-paint-brush',
		'fa-paper-plane',
		'fa-paper-plane-o',
		'fa-paperclip',
		'fa-paragraph',
		'fa-paste',
		'fa-pause',
		'fa-pause-circle',
		'fa-pause-circle-o',
		'fa-paw',
		'fa-paypal',
		'fa-pencil',
		'fa-pencil-square',
		'fa-pencil-square-o',
		'fa-percent',
		'fa-phone',
		'fa-phone-square',
		'fa-photo',
		'fa-picture-o',
		'fa-pie-chart',
		'fa-pied-piper',
		'fa-pied-piper-alt',
		'fa-pinterest',
		'fa-pinterest-p',
		'fa-pinterest-square',
		'fa-plane',
		'fa-play',
		'fa-play-circle',
		'fa-play-circle-o',
		'fa-plug',
		'fa-plus',
		'fa-plus-circle',
		'fa-plus-square',
		'fa-plus-square-o',
		'fa-power-off',
		'fa-print',
		'fa-product-hunt',
		'fa-puzzle-piece',
		'fa-qq',
		'fa-qrcode',
		'fa-question',
		'fa-question-circle',
		'fa-quote-left',
		'fa-quote-right',
		'fa-ra',
		'fa-random',
		'fa-rebel',
		'fa-recycle',
		'fa-reddit',
		'fa-reddit-alien',
		'fa-reddit-square',
		'fa-refresh',
		'fa-registered',
		'fa-remove',
		'fa-renren',
		'fa-reorder',
		'fa-repeat',
		'fa-reply',
		'fa-reply-all',
		'fa-retweet',
		'fa-rmb',
		'fa-road',
		'fa-rocket',
		'fa-rotate-left',
		'fa-rotate-right',
		'fa-rouble',
		'fa-rss',
		'fa-rss-square',
		'fa-rub',
		'fa-ruble',
		'fa-rupee',
		'fa-safari',
		'fa-save',
		'fa-scissors',
		'fa-scribd',
		'fa-search',
		'fa-search-minus',
		'fa-search-plus',
		'fa-sellsy',
		'fa-send',
		'fa-send-o',
		'fa-server',
		'fa-share',
		'fa-share-alt',
		'fa-share-alt-square',
		'fa-share-square',
		'fa-share-square-o',
		'fa-shekel',
		'fa-sheqel',
		'fa-shield',
		'fa-ship',
		'fa-shirtsinbulk',
		'fa-shopping-bag',
		'fa-shopping-basket',
		'fa-shopping-cart',
		'fa-sign-in',
		'fa-sign-out',
		'fa-signal',
		'fa-simplybuilt',
		'fa-sitemap',
		'fa-skyatlas',
		'fa-skype',
		'fa-slack',
		'fa-sliders-h',
		'fa-slideshare',
		'fa-smile-o',
		'fa-soccer-ball-o',
		'fa-sort',
		'fa-sort-alpha-asc',
		'fa-sort-alpha-desc',
		'fa-sort-amount-asc',
		'fa-sort-amount-desc',
		'fa-sort-asc',
		'fa-sort-desc',
		'fa-sort-down',
		'fa-sort-numeric-asc',
		'fa-sort-numeric-desc',
		'fa-sort-up',
		'fa-soundcloud',
		'fa-space-shuttle',
		'fa-spinner',
		'fa-spoon',
		'fa-spotify',
		'fa-square',
		'fa-square-o',
		'fa-stack-exchange',
		'fa-stack-overflow',
		'fa-star',
		'fa-star-half',
		'fa-star-half-empty',
		'fa-star-half-full',
		'fa-star-half-o',
		'fa-star-o',
		'fa-steam',
		'fa-steam-square',
		'fa-step-backward',
		'fa-step-forward',
		'fa-stethoscope',
		'fa-sticky-note',
		'fa-sticky-note-o',
		'fa-stop',
		'fa-stop-circle',
		'fa-stop-circle-o',
		'fa-street-view',
		'fa-strikethrough',
		'fa-stumbleupon',
		'fa-stumbleupon-circle',
		'fa-subscript',
		'fa-subway',
		'fa-suitcase',
		'fa-sun-o',
		'fa-superscript',
		'fa-support',
		'fa-table',
		'fa-tablet',
		'fa-tachometer',
		'fa-tag',
		'fa-tags',
		'fa-tasks',
		'fa-taxi',
		'fa-television',
		'fa-tencent-weibo',
		'fa-terminal',
		'fa-text-height',
		'fa-text-width',
		'fa-th',
		'fa-th-large',
		'fa-th-list',
		'fa-thumb-tack',
		'fa-thumbs-down',
		'fa-thumbs-o-down',
		'fa-thumbs-o-up',
		'fa-thumbs-up',
		'fa-ticket',
		'fa-times',
		'fa-times-circle',
		'fa-times-circle-o',
		'fa-tint',
		'fa-toggle-down',
		'fa-toggle-left',
		'fa-toggle-off',
		'fa-toggle-on',
		'fa-toggle-right',
		'fa-toggle-up',
		'fa-trademark',
		'fa-train',
		'fa-transgender',
		'fa-transgender-alt',
		'fa-trash',
		'fa-trash-o',
		'fa-tree',
		'fa-trello',
		'fa-tripadvisor',
		'fa-trophy',
		'fa-truck',
		'fa-try',
		'fa-tty',
		'fa-tumblr',
		'fa-tumblr-square',
		'fa-turkish-lira',
		'fa-tv',
		'fa-twitch',
		'fa-twitter',
		'fa-twitter-square',
		'fa-umbrella',
		'fa-underline',
		'fa-undo',
		'fa-university',
		'fa-unlink',
		'fa-unlock',
		'fa-unlock-alt',
		'fa-unsorted',
		'fa-upload',
		'fa-usb',
		'fa-usd',
		'fa-user',
		'fa-user-md',
		'fa-user-plus',
		'fa-user-secret',
		'fa-user-times',
		'fa-users',
		'fa-venus',
		'fa-venus-double',
		'fa-venus-mars',
		'fa-viacoin',
		'fa-video-camera',
		'fa-vimeo',
		'fa-vimeo-square',
		'fa-vine',
		'fa-vk',
		'fa-volume-down',
		'fa-volume-off',
		'fa-volume-up',
		'fa-warning',
		'fa-wechat',
		'fa-weibo',
		'fa-weixin',
		'fa-whatsapp',
		'fa-wheelchair',
		'fa-wifi',
		'fa-wikipedia-w',
		'fa-windows',
		'fa-won',
		'fa-wordpress',
		'fa-wrench',
		'fa-xing',
		'fa-xing-square',
		'fa-y-combinator',
		'fa-y-combinator-square',
		'fa-yahoo',
		'fa-yc',
		'fa-yc-square',
		'fa-yelp',
		'fa-yen',
		'fa-youtube',
		'fa-youtube-play',
		'fa-youtube-square',
		// New
		'fa-address-book',
		'fa-address-book-o',
		'fa-address-card',
		'fa-address-card-o',
		'fa-vcard',
		'fa-vcard-o',
		'fa-bandcamp',
		'fa-bathtub',
		'fa-s15',
		'fa-bath',
		'fa-id-card',
		'fa-drivers-license-o',
		'fa-id-card-o',
		'fa-eercast',
		'fa-envelope-open',
		'fa-envelope-open-o',
		'fa-etsy',
		'fa-free-code-camp',
		'fa-grav',
		'fa-handshake-o',
		'fa-id-badge',
		'fa-id-card-o',
		'fa-imdb',
		'fa-linode',
		'fa-meetup',
		'fa-microchip',
		'fa-podcast',
		'fa-quora',
		'fa-ravelry',
		'fa-shower',
		'fa-snowflake-o',
		'fa-superpowers',
		'fa-telegram',
		'fa-thermometer',
		'fa-thermometer-full',
		'fa-thermometer-4',
		'fa-thermometer-3',
		'fa-thermometer-three-quarters',
		'fa-thermometer-2',
		'fa-thermometer-half',
		'fa-thermometer-1',
		'fa-thermometer-quarter',
		'fa-thermometer-0',
		'fa-thermometer-empty',
		'fa-window-close',
		'fa-window-close-o',
		'fa-user-circle',
		'fa-user-circle-o',
		'fa-user-o',
		'fa-window-maximize',
		'fa-window-restore',
		'fa-wpexplorer'
	);

	/**
	 * Fontawesome icons array.
	 *
	 * @var		array	Fontawesome icons.
	 * @since	2.0.0
	 */
	private $icons = array();


	/**
	 * Constructor function.
	 *
	 * @return 	void
	 * @since	2.0.0
	 */
	public function __construct($version = 5)
	{
		if ($version === 4)
		{
			$this->icons = $this->fa_class_lists;
		}
		elseif ($version === 5)
		{
			$this->icons = $this->fa5_classes;
		}
	}

	/**
	 * Get icon list.
	 *
	 * @param	int		$version	The fontawesome version.
	 *
	 * @return 	array	Fontawesome icons.
	 * @Since	1.0.0
	 */
	public function getIcons()
	{
		return $this->icons;
	}

	/**
	 * Add icon into the array.
	 *
	 * @param	string	$icon	The icon class
	 *
	 * @return	void
	 * @since	2.0.0
	 */
	public function addIcon($icon)
	{
		$this->icons[] = $icon;
	}
}
